import tabulate


class HeadingLevels:
    H1 = "="
    H2 = "-"
    H3 = "^"
    H4 = "~"
    H5 = '"'
    H6 = "'"


class RstWriter:
    def __init__(self):
        self.lines = [
            ".. This file is generated by a script. Do not edit it manually.\n\n",
        ]

    def title(self, title, level=HeadingLevels.H1):
        self.lines.append(str(title))
        self.lines.append(f"{level * len(title)}\n")

    def file_version_label(self, version):
        self.lines.append(f":File Version: {version}\n")

    def table(self, table, headers):
        self.lines.append(
            tabulate.tabulate(table, headers=headers, tablefmt="rst") + "\n"
        )

    def text(self, text):
        self.lines.append(text)

    def raw(self, text):
        self.lines.append(text)

    def write(self, file):
        file.write("\n".join(self.lines))
        file.write("\n")
